name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 4 * * *"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci --force
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps --force
      - name: Run Playwright API Tests
        run: npm run AllTests
      - name: Upload Monocart Report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: playwright-monocart-report
          path: playwright-report/report.html
          retention-days: 30
